$ErrorActionPreference = "Stop"
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
New-Item -ItemType Directory -Force -Path 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints' | Out-Null
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed123_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed42_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/agem_distill_nodistill/checkpoints/permuted_mnist_agem_distill_nodistill_seed456_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed123_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed123_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed42_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed42_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_der_nodistill_seed456_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/der_nodistill/checkpoints/permuted_mnist_der_nodistill_seed456_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed123_task9.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task0.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task0.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task1.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task1.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task2.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task2.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task3.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task3.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task4.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task4.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task5.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task5.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task6.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task6.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task7.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task7.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task8.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task8.pt'
Move-Item -LiteralPath 'results/epoch_1/baselines/no_fwt/misc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task9.pt' -Destination 'results/epoch_1/ablations/interactions/datasets/permuted_mnist/methods/er_ewc_noewc/checkpoints/permuted_mnist_er_ewc_noewc_seed42_task9.pt'