"""Detailed chart-by-chart knowledge for the dashboard copilot."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ChartKnowledgeEntry:
    chart_id: str
    kind: str
    title: str
    tab: str
    section: str
    aliases: tuple[str, ...]
    what_it_shows: str
    why_it_matters: str
    reading_hint: str
    caveat: str


CHART_LIBRARY: dict[str, ChartKnowledgeEntry] = {
    "recommendation_breakdown": ChartKnowledgeEntry(
        chart_id="recommendation_breakdown",
        kind="score_breakdown",
        title="Constraint-Adjusted Recommendation Score Breakdown",
        tab="Recommendation",
        section="Recommended method rationale",
        aliases=(
            "recommendation breakdown",
            "score breakdown",
            "score contribution chart",
            "constraint-adjusted recommendation score breakdown",
        ),
        what_it_shows="This chart decomposes the winning recommendation score into additive components like accuracy, forgetting target fit, runtime fit, memory fit, and smaller policy bonuses.",
        why_it_matters="It explains why the current recommendation won under the active request instead of just announcing the winner.",
        reading_hint="Large positive bars are the main reasons the winner survives the current constraints; a missing or small bar means that factor is not doing much work in the current request.",
        caveat="This is a request-specific explanation chart, not a global leaderboard chart.",
    ),
    "case_shortlist_chart": ChartKnowledgeEntry(
        chart_id="case_shortlist_chart",
        kind="shortlist",
        title="Saved Case-Study Shortlist Chart",
        tab="Recommendation",
        section="Case study browser",
        aliases=(
            "shortlist chart",
            "case study shortlist",
            "saved shortlist",
            "top-3 shortlist chart",
            "case-study chart",
        ),
        what_it_shows="This chart compares the ranked shortlist for one saved reproducible request, including score, accuracy, forgetting, runtime, and memory proxy.",
        why_it_matters="It shows the nearest alternatives to the winner in a fixed scenario, which is useful for understanding whether the top choice was dominant or only narrowly ahead.",
        reading_hint="Treat it as a local ranking for one scenario: the gap to rank 2 matters more here than the gap to methods that never made the shortlist.",
        caveat="This chart is tied to the selected saved case and does not necessarily match the exact live controls unless the same case is selected.",
    ),
    "decision_flow_main": ChartKnowledgeEntry(
        chart_id="decision_flow_main",
        kind="decision_flow",
        title="Decision Flow Alluvial Chart",
        tab="Decision Tree",
        section="Interactive alluvial flow",
        aliases=(
            "decision flow",
            "decision tree",
            "alluvial chart",
            "green flow chart",
            "grey flow chart",
            "gray flow chart",
        ),
        what_it_shows="This is the interactive alluvial decision view that traces how dataset, memory, compute, retention, similarity, and joint-retraining settings feed into a recommendation bucket.",
        why_it_matters="It gives users a structural explanation of how the deterministic recommendation engine behaves across nearby constraint regimes instead of only reporting a single winner.",
        reading_hint="Green flow is the active path for the current controls; the grey context flows show the neighboring branches that remain available under nearby settings.",
        caveat="This is a bucketed visual explanation layer over the engine, not a second independent recommender.",
    ),
    "decision_tree_breakdown": ChartKnowledgeEntry(
        chart_id="decision_tree_breakdown",
        kind="score_breakdown",
        title="Decision-Tree Path Score Breakdown",
        tab="Decision Tree",
        section="Active leaf explanation",
        aliases=(
            "decision tree breakdown",
            "decision flow breakdown",
            "active leaf breakdown",
        ),
        what_it_shows="This breakdown reuses the recommendation score decomposition for the leaf currently selected in the decision-flow tab.",
        why_it_matters="It confirms that the alluvial tree and the recommendation panel are reading from the same scoring policy.",
        reading_hint="If this breakdown changes while the flow path changes, that is the expected coupling between the visual tree and the underlying engine.",
        caveat="It is the same scoring logic shown in a different tab, not a different analysis.",
    ),
    "comparison_grouped_bars": ChartKnowledgeEntry(
        chart_id="comparison_grouped_bars",
        kind="grouped_metrics",
        title="Grouped Metric Comparison Bars",
        tab="Method Comparison",
        section="Method summary overview",
        aliases=(
            "comparison grouped bars",
            "grouped metric bars",
            "metric comparison bars",
            "comparison bar chart",
        ),
        what_it_shows="This chart places average accuracy, forgetting, runtime, and memory proxy side by side so methods can be compared across several dimensions at once.",
        why_it_matters="It is the quickest visual summary of whether a method is balanced, accuracy-heavy, runtime-heavy, or memory-heavy.",
        reading_hint="Use it to spot lopsided methods first, then confirm the more important trade-offs in the scatter plots below.",
        caveat="Because multiple metrics are mixed together, it is an overview chart rather than the final word on any single metric.",
    ),
    "comparison_acc_forgetting": ChartKnowledgeEntry(
        chart_id="comparison_acc_forgetting",
        kind="accuracy_forgetting",
        title="Method Comparison: Accuracy vs Forgetting",
        tab="Method Comparison",
        section="Core retention trade-off",
        aliases=(
            "comparison accuracy vs forgetting",
            "method comparison accuracy vs forgetting",
            "core retention trade-off",
        ),
        what_it_shows="This is the main within-dataset retention frontier in the comparison tab: methods that sit higher and further left combine stronger final performance with lower forgetting.",
        why_it_matters="It is one of the most important charts for continual learning because it directly visualizes the tension between remembering old tasks and performing well overall.",
        reading_hint="Upper-left is desirable; if two methods are close, use the significance and effect-size matrices before claiming a real separation.",
        caveat="This chart is filtered by the current dataset and method-family settings, so it is not a global cross-dataset view.",
    ),
    "comparison_acc_runtime": ChartKnowledgeEntry(
        chart_id="comparison_acc_runtime",
        kind="accuracy_runtime",
        title="Method Comparison: Accuracy vs Runtime",
        tab="Method Comparison",
        section="Compute trade-off",
        aliases=(
            "comparison accuracy vs runtime",
            "method comparison accuracy vs runtime",
            "comparison accuracy vs time",
        ),
        what_it_shows="This chart compares how much mean accuracy each method buys for its runtime in the selected dataset.",
        why_it_matters="It helps identify methods that are efficient enough to justify their cost, especially when two methods have similar retention but very different runtimes.",
        reading_hint="High-and-left is attractive when compute matters; far-right methods need a clear accuracy or retention reason to justify themselves.",
        caveat="Runtime is descriptive here and should not be treated as a statistical claim metric in the same way as accuracy or forgetting.",
    ),
    "comparison_acc_memory": ChartKnowledgeEntry(
        chart_id="comparison_acc_memory",
        kind="accuracy_memory",
        title="Method Comparison: Accuracy vs Memory Proxy",
        tab="Method Comparison",
        section="Storage trade-off",
        aliases=(
            "comparison accuracy vs memory",
            "comparison accuracy vs estimated memory",
            "comparison accuracy vs memory proxy",
        ),
        what_it_shows="This chart compares the selected dataset's method accuracy against the study's estimated storage footprint proxy.",
        why_it_matters="It highlights which methods are still competitive when storage is constrained, especially replay-heavy methods whose quality may depend on memory budget.",
        reading_hint="Upper-left is desirable, but remember that the x-axis is proxy-estimated from configuration rather than measured device telemetry.",
        caveat="This is not a measured peak-VRAM plot.",
    ),
    "comparison_significance_matrix": ChartKnowledgeEntry(
        chart_id="comparison_significance_matrix",
        kind="significance",
        title="Holm-Adjusted Pairwise p-value Matrix",
        tab="Method Comparison",
        section="Within-dataset significance view",
        aliases=(
            "significance matrix",
            "pairwise p-value matrix",
            "holm-adjusted matrix",
            "comparison significance matrix",
        ),
        what_it_shows="This matrix displays the Holm-adjusted pairwise p-values for the selected dataset and metric family.",
        why_it_matters="It tells you which method differences still survive multiple-comparison correction instead of disappearing once you stop doing naive pairwise reading.",
        reading_hint="Low cells indicate stronger evidence that the row and column methods differ on the selected metric; diagonal cells are trivial self-comparisons.",
        caveat="This should always be interpreted alongside effect size because significance alone does not reveal practical magnitude.",
    ),
    "comparison_effect_matrix": ChartKnowledgeEntry(
        chart_id="comparison_effect_matrix",
        kind="effect",
        title="Rank-Biserial Effect-Size Matrix",
        tab="Method Comparison",
        section="Within-dataset effect-size view",
        aliases=(
            "effect matrix",
            "effect-size matrix",
            "rank-biserial matrix",
            "comparison effect matrix",
        ),
        what_it_shows="This matrix shows the direction and magnitude of pairwise differences for the selected metric using rank-biserial effect size.",
        why_it_matters="It complements the significance matrix by telling you whether a difference is tiny, moderate, or large in practical terms.",
        reading_hint="Positive cells favor the row method; negative cells favor the column method; large-magnitude cells matter more than marginal near-zero cells.",
        caveat="A large effect without statistical support and a significant tiny effect should both be read cautiously rather than overclaimed.",
    ),
    "comparison_pareto": ChartKnowledgeEntry(
        chart_id="comparison_pareto",
        kind="pareto",
        title="Non-Joint Pareto Candidates",
        tab="Method Comparison",
        section="Non-dominated frontier",
        aliases=(
            "pareto chart",
            "comparison pareto",
            "pareto frontier",
            "non-joint pareto",
        ),
        what_it_shows="This chart keeps only non-joint methods that are not dominated on the study's chosen trade-off dimensions.",
        why_it_matters="It is useful for narrowing a large method set down to the options that remain defensible under a multi-objective view.",
        reading_hint="If a method is missing here, it means another non-joint method matched or beat it on all included dimensions.",
        caveat="Joint training is intentionally excluded from this Pareto view by study policy.",
    ),
    "ablation_runtime": ChartKnowledgeEntry(
        chart_id="ablation_runtime",
        kind="ablation_runtime",
        title="Ablation Runtime Sensitivity",
        tab="Method Comparison",
        section="Ablation Context Explorer",
        aliases=(
            "ablation runtime chart",
            "runtime sensitivity chart",
            "ablation compute chart",
        ),
        what_it_shows="This chart compares how ablation variants changed total runtime for the selected ablation dataset.",
        why_it_matters="It helps explain the engineering cost of mechanism changes such as buffer size, regularization strength, or interaction terms.",
        reading_hint="Use hover to inspect seeds completed and task-time summaries rather than reading it as a pure performance plot.",
        caveat="This is secondary ablation context, not a primary-study ranking chart.",
    ),
    "ablation_memory": ChartKnowledgeEntry(
        chart_id="ablation_memory",
        kind="ablation_memory",
        title="Ablation Memory Sensitivity",
        tab="Method Comparison",
        section="Ablation Context Explorer",
        aliases=(
            "ablation memory chart",
            "memory sensitivity chart",
            "ablation memory proxy",
        ),
        what_it_shows="This chart visualizes memory-relevant ablation settings such as replay buffer and batch size for the selected ablation dataset.",
        why_it_matters="It helps connect performance behavior to memory-sensitive configuration choices without pretending to be measured hardware telemetry.",
        reading_hint="Treat the x-axis and hover text as configuration context rather than exact hardware consumption measurements.",
        caveat="This is a proxy view, not measured peak VRAM.",
    ),
    "ablation_robustness": ChartKnowledgeEntry(
        chart_id="ablation_robustness",
        kind="robustness",
        title="Resume/Restart Robustness Scatter",
        tab="Method Comparison",
        section="Ablation Context Explorer",
        aliases=(
            "robustness chart",
            "resume robustness chart",
            "restart robustness chart",
            "ablation robustness",
        ),
        what_it_shows="This scatter shows how resumed runs shifted relative to their primary-study counterparts in the ablation context dataset.",
        why_it_matters="It tells you whether interruption and resume behavior meaningfully changed the recovered result.",
        reading_hint="Points close to zero are reassuring because the resumed run stayed near the original result.",
        caveat="This is about pipeline reliability, not headline method superiority.",
    ),
    "visuals_heatmap_aa": ChartKnowledgeEntry(
        chart_id="visuals_heatmap_aa",
        kind="heatmap_accuracy",
        title="Cross-Dataset Average Accuracy Heatmap",
        tab="Dataset Visuals",
        section="Cross-dataset overview",
        aliases=(
            "accuracy heatmap",
            "cross-dataset accuracy heatmap",
            "average accuracy heatmap",
        ),
        what_it_shows="This heatmap shows where average accuracy is strongest across the full dataset-method matrix.",
        why_it_matters="It is the quickest way to see which methods are broadly strong and which datasets remain difficult across the board.",
        reading_hint="Look for rows or columns that stay strong across many cells before making claims about consistency.",
        caveat="This is a descriptive overview; it does not replace per-dataset significance analysis.",
    ),
    "visuals_heatmap_forgetting": ChartKnowledgeEntry(
        chart_id="visuals_heatmap_forgetting",
        kind="heatmap_forgetting",
        title="Cross-Dataset Forgetting Heatmap",
        tab="Dataset Visuals",
        section="Cross-dataset retention overview",
        aliases=(
            "forgetting heatmap",
            "cross-dataset forgetting heatmap",
            "retention heatmap",
        ),
        what_it_shows="This heatmap shows where forgetting remains low or high across the full study matrix.",
        why_it_matters="It helps separate methods that achieve strong final accuracy by retaining well from those that pay for it with forgetting.",
        reading_hint="Lower forgetting is preferable, so interpret this as a retention map rather than a conventional leaderboard.",
        caveat="Comparing this heatmap alone can be misleading unless you also inspect the matching accuracy view.",
    ),
    "visuals_acc_forgetting": ChartKnowledgeEntry(
        chart_id="visuals_acc_forgetting",
        kind="accuracy_forgetting",
        title="Dataset Visuals: Accuracy vs Forgetting",
        tab="Dataset Visuals",
        section="Selected dataset trade-off",
        aliases=(
            "dataset visuals accuracy vs forgetting",
            "selected dataset accuracy vs forgetting",
            "visuals accuracy vs forgetting",
        ),
        what_it_shows="This is the selected dataset's dedicated retention frontier inside the Dataset Visuals tab.",
        why_it_matters="It gives a cleaner dataset-specific view than the broader comparison workspace when the goal is to understand one benchmark deeply.",
        reading_hint="Upper-left is desirable, and hover helps identify whether a point is a leader or part of the top cluster.",
        caveat="This view changes with the selected dataset and family filters, so compare like-for-like before drawing conclusions.",
    ),
    "visuals_acc_runtime": ChartKnowledgeEntry(
        chart_id="visuals_acc_runtime",
        kind="accuracy_runtime",
        title="Dataset Visuals: Accuracy vs Runtime",
        tab="Dataset Visuals",
        section="Selected dataset compute trade-off",
        aliases=(
            "dataset visuals accuracy vs runtime",
            "selected dataset accuracy vs runtime",
            "visuals accuracy vs runtime",
        ),
        what_it_shows="This chart shows how runtime scales against accuracy for the currently selected dataset.",
        why_it_matters="It is useful when you want to understand which methods are accuracy-efficient inside one benchmark instead of across all of them.",
        reading_hint="Methods high and left are especially attractive when compute is limited.",
        caveat="Runtime is descriptive and should be interpreted alongside accuracy and forgetting, not alone.",
    ),
    "visuals_acc_memory": ChartKnowledgeEntry(
        chart_id="visuals_acc_memory",
        kind="accuracy_memory",
        title="Dataset Visuals: Accuracy vs Memory Proxy",
        tab="Dataset Visuals",
        section="Selected dataset storage trade-off",
        aliases=(
            "dataset visuals accuracy vs memory",
            "dataset visuals accuracy vs memory proxy",
            "selected dataset accuracy vs estimated memory",
        ),
        what_it_shows="This chart compares the selected dataset's methods by accuracy against the study's proxy-estimated storage footprint.",
        why_it_matters="It is where you can see whether the selected dataset rewards replay-heavy methods enough to justify their storage footprint.",
        reading_hint="Treat the x-axis as a relative storage burden rather than literal device memory telemetry.",
        caveat="The memory axis is proxy-estimated from configuration, not measured hardware usage.",
    ),
    "visuals_rank_slope": ChartKnowledgeEntry(
        chart_id="visuals_rank_slope",
        kind="rank_slope",
        title="Method Rank Slope Chart",
        tab="Dataset Visuals",
        section="Cross-dataset ranking shifts",
        aliases=(
            "rank slope chart",
            "method rank slope",
            "ranking shifts chart",
            "slope chart",
        ),
        what_it_shows="This chart tracks how each method's accuracy rank changes as the dataset changes.",
        why_it_matters="It reveals which methods are stable generalists and which methods are highly dataset-sensitive.",
        reading_hint="Lower lines are better because the y-axis is rank; steep movement means the method's standing changes sharply across datasets.",
        caveat="Rank compresses absolute differences, so use it with the heatmaps or per-dataset scatters.",
    ),
    "visuals_top_cluster": ChartKnowledgeEntry(
        chart_id="visuals_top_cluster",
        kind="top_cluster",
        title="Top-Cluster Membership Chart",
        tab="Dataset Visuals",
        section="Cross-dataset competitiveness summary",
        aliases=(
            "top cluster chart",
            "top-cluster membership chart",
            "cluster membership chart",
        ),
        what_it_shows="This chart counts how many datasets kept each method inside the non-inferior cluster around the leader.",
        why_it_matters="It is a consistency chart: methods that appear often here are repeatedly competitive even if they do not dominate every dataset.",
        reading_hint="Higher bars mean broader competitiveness; hover gives the mean rank and mean accuracy context behind that count.",
        caveat="A frequent top-cluster method is not necessarily the absolute best method in every dataset.",
    ),
    "static_avg_accuracy_heatmap": ChartKnowledgeEntry(
        chart_id="static_avg_accuracy_heatmap",
        kind="heatmap_accuracy",
        title="Saved Static Average-Accuracy Heatmap",
        tab="Dataset Visuals",
        section="Saved Figure Gallery",
        aliases=("saved static accuracy heatmap", "static average accuracy heatmap"),
        what_it_shows="This is the archived saved heatmap for average accuracy that mirrors the generated study figure.",
        why_it_matters="It provides parity with the saved study artifacts so the dashboard and the generated figures can be cross-checked.",
        reading_hint="Interpret it the same way as the interactive accuracy heatmap, but remember it is a fixed artifact rather than a filtered live view.",
        caveat="Because this is a static image, it will not reflect live dashboard filters.",
    ),
    "static_forgetting_heatmap": ChartKnowledgeEntry(
        chart_id="static_forgetting_heatmap",
        kind="heatmap_forgetting",
        title="Saved Static Forgetting Heatmap",
        tab="Dataset Visuals",
        section="Saved Figure Gallery",
        aliases=("saved static forgetting heatmap", "static forgetting heatmap"),
        what_it_shows="This is the archived saved forgetting heatmap that mirrors the generated study artifact.",
        why_it_matters="It keeps the dashboard aligned with the saved report figures while still offering a quick visual retention summary.",
        reading_hint="Read it as a retention map just like the interactive forgetting heatmap.",
        caveat="Because this is a static image, it does not change with live filters.",
    ),
    "static_accuracy_vs_forgetting": ChartKnowledgeEntry(
        chart_id="static_accuracy_vs_forgetting",
        kind="accuracy_forgetting",
        title="Saved Static Accuracy vs Forgetting Figure",
        tab="Dataset Visuals",
        section="Saved Figure Gallery",
        aliases=("static accuracy vs forgetting", "saved accuracy vs forgetting figure"),
        what_it_shows="This is the archived dataset-level accuracy-vs-forgetting figure from the saved study outputs.",
        why_it_matters="It lets the user compare the live scatter and the saved figure that would appear in the study outputs.",
        reading_hint="Interpret it like the interactive retention frontier, but use it mainly for artifact parity rather than fresh analysis.",
        caveat="This image does not respond to live filters or hover inspection.",
    ),
    "static_accuracy_vs_runtime": ChartKnowledgeEntry(
        chart_id="static_accuracy_vs_runtime",
        kind="accuracy_runtime",
        title="Saved Static Accuracy vs Runtime Figure",
        tab="Dataset Visuals",
        section="Saved Figure Gallery",
        aliases=("static accuracy vs runtime", "saved accuracy vs runtime figure"),
        what_it_shows="This is the archived dataset-level accuracy-vs-runtime trade-off figure from the saved study outputs.",
        why_it_matters="It keeps the dashboard visually aligned with the generated study figures.",
        reading_hint="Use it as a fixed reference view of the runtime trade-off rather than a live exploratory chart.",
        caveat="This image does not respond to dashboard filters.",
    ),
    "static_accuracy_vs_memory": ChartKnowledgeEntry(
        chart_id="static_accuracy_vs_memory",
        kind="accuracy_memory",
        title="Saved Static Accuracy vs Memory Figure",
        tab="Dataset Visuals",
        section="Saved Figure Gallery",
        aliases=("static accuracy vs memory", "saved accuracy vs memory figure"),
        what_it_shows="This is the archived dataset-level accuracy-vs-memory trade-off figure from the saved study outputs.",
        why_it_matters="It preserves parity with the saved analysis package while still showing the same core storage trade-off.",
        reading_hint="Interpret it like the interactive memory scatter, keeping in mind that the x-axis is still a proxy memory estimate.",
        caveat="This image is static and does not reflect current live filter state.",
    ),
    "report_friedman": ChartKnowledgeEntry(
        chart_id="report_friedman",
        kind="friedman_rank",
        title="Friedman Average-Rank Summary",
        tab="Report/About",
        section="Cross-dataset ranking summary",
        aliases=(
            "friedman chart",
            "friedman average rank chart",
            "report friedman chart",
        ),
        what_it_shows="This chart summarizes the cross-dataset Friedman ranking result using average method rank.",
        why_it_matters="It gives a compact secondary summary of overall ranking behavior across datasets.",
        reading_hint="Lower average rank is better, but treat the result as descriptive support for the per-dataset evidence rather than a replacement for it.",
        caveat="The study only has four datasets, so this chart should be read cautiously and secondarily.",
    ),
    "report_ablation_runtime": ChartKnowledgeEntry(
        chart_id="report_ablation_runtime",
        kind="ablation_runtime",
        title="Report Ablation Runtime Chart",
        tab="Report/About",
        section="Ablation context",
        aliases=("report ablation runtime", "report runtime chart"),
        what_it_shows="This report-level chart summarizes how representative ablation families changed compute cost in the selected ablation dataset.",
        why_it_matters="It gives a compact supporting view of engineering cost in the report tab.",
        reading_hint="Read it as supporting evidence for mechanism cost rather than as a new leaderboard.",
        caveat="This remains secondary ablation context.",
    ),
    "report_ablation_robustness": ChartKnowledgeEntry(
        chart_id="report_ablation_robustness",
        kind="robustness",
        title="Report Resume/Restart Robustness Chart",
        tab="Report/About",
        section="Ablation context",
        aliases=("report robustness chart", "report resume robustness", "report restart robustness"),
        what_it_shows="This report-level chart summarizes how restart/resume runs deviated from the primary-study runs.",
        why_it_matters="It provides a compact trustworthiness check in the narrative report tab.",
        reading_hint="Near-zero deviation is what you want to see when resume robustness is healthy.",
        caveat="This chart is about experimental pipeline reliability, not method ranking quality.",
    ),
}


FAMILY_ALIASES: dict[str, tuple[str, ...]] = {
    "score_breakdown": ("score breakdown", "score contribution", "breakdown"),
    "shortlist": ("shortlist", "top-3 shortlist", "top 3 shortlist", "case study", "case-study"),
    "decision_flow": ("decision tree", "decision flow", "alluvial"),
    "grouped_metrics": ("grouped metric", "metric bars", "grouped bar"),
    "accuracy_forgetting": ("accuracy vs forgetting", "retention frontier"),
    "accuracy_runtime": ("accuracy vs runtime", "accuracy vs time", "compute time"),
    "accuracy_memory": ("accuracy vs memory", "accuracy vs estimated memory", "accuracy vs memory proxy"),
    "significance": ("significance matrix", "pairwise p", "p-values", "holm-adjusted", "holm corrected"),
    "effect": ("effect-size matrix", "effect size", "rank-biserial"),
    "pareto": ("pareto", "frontier"),
    "heatmap_accuracy": ("accuracy heatmap", "average accuracy heatmap"),
    "heatmap_forgetting": ("forgetting heatmap", "retention heatmap"),
    "rank_slope": ("rank slope", "slope chart", "ranking shifts"),
    "top_cluster": ("top cluster", "top-cluster", "cluster membership"),
    "friedman_rank": ("friedman", "average rank", "cross-dataset ranking"),
    "ablation_runtime": ("ablation runtime", "runtime sensitivity"),
    "ablation_memory": ("ablation memory", "memory sensitivity"),
    "robustness": ("robustness", "resume", "restart"),
}


def find_chart_entry(text: str) -> ChartKnowledgeEntry | None:
    lowered = text.lower()
    entries = sorted(CHART_LIBRARY.values(), key=lambda item: max(len(alias) for alias in item.aliases), reverse=True)
    for entry in entries:
        if any(alias in lowered for alias in entry.aliases):
            return entry
    return None

